### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by jbcrail**

### CODE REVIEW

**Comment by martindurant** [comment]
No need for a +1 on this PR, merge when you are happy.

**Comment by jbcrail** [comment]
Thanks!

**Comment by martindurant** [comment]
We need to actually turn on RTD for intake-netflow, right?

**Comment by jbcrail** [comment]
Yes. I didn't know about this.

**Comment by seibert** [comment]
RTD is enabled, but you'll need to add a YAML config in the repo to enable the use of conda environments for documentation building, like we have for pcap:

https://github.com/ContinuumIO/intake-pcap/blob/master/readthedocs.yml

**Comment by jbcrail** [comment]
Thanks. I've copied and committed the config.

**Pull request merged**
